---
# tasks file for common

- name: set timezone to Europe/Moscow
  timezone:
    name: "{{ region }}/{{ city }}"

- block:
    - name: create a file for swap
      shell: fallocate -l {{ swap_size }} {{ swap_file }}
      args:
        creates: "{{ swap_file }}"

    - name: set the correct permissions
      file:
        path: /swapfile
        owner: root
        group: root
        mode: '0600'

    - name: turn the file into a swap file
      shell: mkswap /swapfile
      when: ansible_facts.swapfree_mb == 0

    - name: enable the swap file
      shell: swapon /swapfile
      when: ansible_facts.swapfree_mb == 0

    - name: add swap file to fstab
      mount:
        name: none
        src: /swapfile
        fstype: swap
        opts: sw
        passno: 0
        dump: 0
        state: present
  become: yes

- name: "change hostname"
  hostname:
    name: "{{ inventory_hostname }}"

- name: update apt cache
  apt:
    update_cache: yes
  become: yes
