---
# tasks file for swaptrasher
- block:
    - name: disable swap
      shell: swapoff -a

    - name: delete swap file
      file:
        path: "{{ swap_file }}"
        state: absent

    - name: remove entry from /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: "^{{ swap_file }}"
        state: absent

  when: ansible_facts.swaptotal_mb > 0
